const Menu = [{
    id:1,
    image:"images/athina.jpg",
    name:"Thena",
    category:"Marvel",
    price:24,
    description:"Thena is a member of the genetically-engineered Eternals. Created by the Celestials in the World Forge, Thena was sent to Centuri-Six and progress the planet's societal development, paving the way for the planet's Emergence. Thena's memory was wiped, and was then sent to Earth with nine other Eternals in 5000 BC for the same goal, with the mission to exterminate the Deviants first. During her time living in Ancient Greece, she became known as the protector of Athens and was incorporated into their mythology as Athena. After recalling traumatizing memories of Centuri-Six's destruction in a Mahd Wy'ry incident, Thena departed with Gilgamesh to live in self-imposed exile in Australia.",
},
{
id:2,
image:"images/avengers.jpg",
name:"Avengers",
category:"Marvel",
price:24,
description:"Marvel's The Avengers 'redirects here. For the original comic book characters, see Avengers (comics). For other uses, see Avenger (disambiguation).",
},
{
    id:3,
    image:"images/avengersa.jpg",
    name:"Avengers",
    category:"Marvel",
    price:24,
    description:"Marvel's The Avengers 'redirects here. For the original comic book characters, see Avengers (comics). For other uses, see Avenger (disambiguation).",
        },
    {
        id:4,
        image:"images/batman.jpg",
        name:"Bat Man",
        category:"DC",
        price:24,
        description:"The Batman is a 2022 American superhero film based on the DC Comics character Batman. Produced by Warner Bros. Pictures, DC Films, 6th & Idaho, and Dylan Clark Productions, and distributed by Warner Bros.",
        },
        {id:5,
            image:"images/batmana.jpg",
            name:"Bat Man",
            category:"DC",
            price:24,
            description:"The Batman is a 2022 American superhero film based on the DC Comics character Batman. Produced by Warner Bros. Pictures, DC Films, 6th & Idaho, and Dylan Clark Productions, and distributed by Warner Bros.",
            },
            {
                  id:6,
                    image:"images/captain_america.jpg",
                    name:"iron man",
                    category:"Avengers",
                    price:25,
                    description:'Iron Man',
                    },{
                        id:1,
                        image:"images/carnagevsvenom.jpg",
                        name:"Daisy",
                        category:"Star Wars",
                        price:24,
                        description:'Star Wars',
                        },   {
                            id:2,
                            image:"images/cyclopes.jpg",
                            name:"Daisy",
                            category:"Star Wars",
                            price:24,
                            description:'Star Wars',
                            },  {
                                id:3,
                                image:"images/daisy.jpg",
                                name:"Daisy",
                                category:"Star Wars",
                                price:24,
                                description:'Star Wars',
                                },  {
                                    id:4,
                                    image:"images/dark.jpg",
                                    name:"Daisy",
                                    category:"Star Wars",
                                    price:24,
                                    description:'Star Wars',
                                    },  {
                                        id:5,
                                        image:"images/deadpool.jpg",
                                        name:"Daisy",
                                        category:"Star Wars",
                                        price:24,
                                        description:'Star Wars',
                                        },  {
                                            id:6,
                                            image:"images/doctor_strange.jpg",
                                            name:"Daisy",
                                            category:"Star Wars",
                                            price:24,
                                            description:'Star Wars',
                                            },  {
                                                id:1,
                                                image:"images/emilia_clark.jpg",
                                                name:"Daisy",
                                                category:"DC",
                                                price:24,
                                                description:'DC',
                                                },   {
                                                    id:2,
                                                    image:"images/flash.jpg",
                                                    name:"Daisy",
                                                    category:"DC",
                                                    price:24,
                                                    description:'Star Wars',
                                                    },  {
                                                        id:3,
                                                        image:"images/funny_avengers.jpg",
                                                        name:"Daisy",
                                                        category:"DC",
                                                        price:24,
                                                        description:'Star Wars',
                                                        },  {
                                                            id:4,
                                                            image:"images/gal_gadot.jpg",
                                                            name:"Daisy",
                                                            category:"DC",
                                                            price:24,
                                                            description:'Star Wars',
                                                            },  {
                                                                id:5,
                                                                image:"images/hell_boy.jpg",
                                                                name:"Daisy",
                                                                category:"DC",
                                                                price:24,
                                                                description:'Star Wars',
                                                                },  {
                                                                    id:6,
                                                                    image:"images/iron_man.jpg",
                                                                    name:"Daisy",
                                                                    category:"DC",
                                                                    price:24,
                                                                    description:'Star Wars',
                                                                    }, {
                                                                        id:6,
                                                                        image:"images/dead.jpg",
                                                                        name:"Daisy",
                                                                        category:"Deadpool",
                                                                        price:24,
                                                                        description:'Star Wars',
                                                                        },  

]
export default Menu;